#pragma once

using namespace ATL;

template <class T>
class CProxy_ITextMessageEvents : public IConnectionPointImpl<T, &__uuidof( _ITextMessageEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
